### ISSUE TITLE
Cannot read waypoints file

### ISSUE THREAD

**Issue by sporella** [JiriRichter/WRFDomainWizard#40]
Hello:

First, I want to thank you for this very useful application. It saved me a lot of time and headaches!

My issue is when I try to upload a waypoints file in gpx format, and I always receive the same error:

`Unable to parse file xxx: TypeError: Cannot read properties of undefined (reading 'parse')` 

Could you provide some clarification about the structure of the file to be uploaded?

Thanks!

**Comment by JiriRichter** [comment]
Hi @sporella, thank you for reporting this issue. From a brief look at the source code it should be able to open waypoint files in WPT, GPX and CUP formats. This part of the code was written over 5 years ago and is not well tested. I tried openening a random file and am getting the same error. I should be able to have it fixed in a few days.

**Comment by JiriRichter** [comment]
@sporella, can I ask how you are intending to use this feature? I originally implemented this to support my specific scenario where I needed to create a domain containing waypoints from WPT files. I have a version which now supports GPX files but will only display the waypoints. I am wondering whether it would also be usefull to display tracks and other features and also add support for more common files like KMZ and GeoJSON.

**Comment by JiriRichter** [comment]
@sporella, I replaced the waypoints tab with geographic files tab. I added support for GeoJSON files since that is directly supported by the mapping library and was easy to do. I added support for GPX but it only displays waypoints. I created a feature request #43 to show all GPX file features but I'm not planning to work on it immediattely. As I understand it, adding support for GeoJSON suits your scenario better. There is no direct support for KMZ/KML in the mapping library but plugins do exist. I will open another feature request for this but again do not plan implementing it anytime soon. Please, let me know if the resolution of this bug does not provide a solution for your scenaio.

**Comment by sporella** [comment]
@JiriRichter I tested the geoJSON feature and it works neatly. Thank you so much for the quick implementation!
