### ISSUE TITLE
add points to drag boundaries from the middle

### ISSUE THREAD

**Issue by HathewayWill** [JiriRichter/WRFDomainWizard#54]
I'd like to see the boundary box have an option to drag from a side not the corners only.  Makes it difficult to fine tune the boundaries.

![image](https://github.com/user-attachments/assets/42ce03ff-4018-4b37-936e-9c70bf8c9cf8)

**Comment by JiriRichter** [comment]
@HathewayWill ,I'm not sure I understand what improvement you would like to see. The corner markers are used for resizing a grid diagonally. To move (drag) a grid you can start by clicking anywhere. Are you proposing to have the option to resize the grid only horizontally/vertically only by clicking on the border instead of the corners?

**Comment by HathewayWill** [comment]
[Screencast from 2024-10-23 19-26-10.webm](https://github.com/user-attachments/assets/9e55af61-3d63-4a46-982d-b68165ed462e)

Say I want to keep the north and south boundaries the same location, but i need to slide east and west a little more. if i slip with my mouse and then adjust the north and south i have to adjust it.

**Comment by JiriRichter** [comment]
I think I get it. I am thinking about adding a new square markers to the middle of the boundary to allow resizing in one direction only.

**Comment by HathewayWill** [comment]
that's what i meant

**Comment by JiriRichter** [comment]
@HathewayWill , I have a PR open for this feature. Please, have a look at https://jiririchter.github.io/WRFDomainWizard/ which currently points to the work branch. It work ok. I noticed the drag does not work sometime on a new grid for certain zoom level. This might be caused by the leaflet lib but I'm not sure. I'm definitely not seeing any errors in a debugger. If you find it working well enough I will complete the PR. I sent you an invite as collaborator. That way I can add you as an approver for PRs like this where I'm not sure it's working properly.

**Comment by HathewayWill** [comment]
> @HathewayWill , I have a PR open for this feature. Please, have a look at https://jiririchter.github.io/WRFDomainWizard/ which currently points to the work branch. It works ok. I noticed the drag does not work sometime on a new grid for certain zoom levels. This might be caused by the leaflet lib but I'm not sure. I'm definitely not seeing any errors in the debugger. If you find it working well enough I will complete the PR. I sent you an invite as collaborator. That way I can add you as an approver for PRs like this where I'm not sure it's working properly.

Looks good to me
