### ISSUE TITLE
Domain Wizard doesn't allow dx or dy resolution to be less than 100 meters

### ISSUE THREAD

**Issue by AlfredZho** [JiriRichter/WRFDomainWizard#58]
The WRF Domain Wizard doesn't allow dx or dy resolution to be less than 100 meters. This shouldn't be the case. It should be allowed to be smaller for use cases where users are working with high resolution datasets.

![wrfdomainwizard](https://github.com/user-attachments/assets/02c60527-8312-4c68-971f-726583b5d18f)

**Comment by JiriRichter** [comment]
Hey @AlfredZho , thanks for logging this bug. I labeled is as enhancement rather than a bug. The number 100 was selected arbitrarily. The WRF best practices do not have any recommendation for the DX/DY min value so I'm going to lower the default min value to 1. This is not necessary but I will make it configurable via the settings tab to test out global settings feature I want to use for other things

**Comment by JiriRichter** [comment]
@AlfredZho, this has been resolved. Can you please check the changes in preview https://jiririchter.github.io/WRFDomainWizard/
